// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpCj3vtgPXyEPas2BxLFD3nshFHH3Ubcs',
    appId: '1:291608509598:web:56170bb9a5f88620724f8f',
    messagingSenderId: '291608509598',
    projectId: 'studyplanner-38d0b',
    authDomain: 'studyplanner-38d0b.firebaseapp.com',
    storageBucket: 'studyplanner-38d0b.firebasestorage.app',
    measurementId: 'G-YDJDXW1SJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF03Z2DNz4EkSHY8t4_GpSwG0MykKK9NY',
    appId: '1:291608509598:android:01790d9059e6177d724f8f',
    messagingSenderId: '291608509598',
    projectId: 'studyplanner-38d0b',
    storageBucket: 'studyplanner-38d0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ZPaBQB5Ia_Vto2-EnQARELwu7p07iaw',
    appId: '1:291608509598:ios:234b9b15a958f811724f8f',
    messagingSenderId: '291608509598',
    projectId: 'studyplanner-38d0b',
    storageBucket: 'studyplanner-38d0b.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ZPaBQB5Ia_Vto2-EnQARELwu7p07iaw',
    appId: '1:291608509598:ios:234b9b15a958f811724f8f',
    messagingSenderId: '291608509598',
    projectId: 'studyplanner-38d0b',
    storageBucket: 'studyplanner-38d0b.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );
}
